[claude-code]
version = "1.0.43"

[gemini-cli]
version = "0.1.9"
src_hash = "sha256-o+AczO0SXnWeXth5gKRadeURLM4RsWvbSYRroXVIx5g="
npm_deps_hash = "sha256-xwW0ZtpTYGirMIpSPGdkbNlVicNzsRDlgeysJKkdyHI="
