[claude-code]
version = "1.0.43"
src_type = "url"
src_hash = "sha256-t8XunDJEt8jdShec4AtelTBmQ3KtWPMOgMxjxuMveRU="
npm_package = "@anthropic-ai/claude-code"

[gemini-cli]
version = "0.1.9"
src_type = "github"
src_hash = "sha256-o+AczO0SXnWeXth5gKRadeURLM4RsWvbSYRroXVIx5g="
npm_deps_hash = "sha256-xwW0ZtpTYGirMIpSPGdkbNlVicNzsRDlgeysJKkdyHI="
github_repo = "google-gemini/gemini-cli"
